[problem]

---


If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.

In [24]:
a = 3
b = 5

sumA = 0
for i in range(int(1000/a)):
  sumA += a * (i+1)

sumB = 0
for i in range(int(1000/a)):
  sumB += b * (i+1)

print('The sum of all the multiples of 3 below 1000 = ' + str(sumA))
print('The sum of all the multiples of 5 below 1000 = ' + str(sumB))
print('The sum of all the multiples of 3 or 5 below 1000 = ' + str(sumA + sumB))

The sum of all the multiples of 3 below 1000 = 166833
The sum of all the multiples of 5 below 1000 = 278055
The sum of all the multiples of 3 or 5 below 1000 = 444888

In [25]:
sum([x for x in range(1000) if x%3 == 0 or x%5 == 0])

233168